FROM golang:alpine as builder

ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

RUN apk add --update --no-cache alpine-sdk bash ca-certificates \
      libressl \
      tar \
      git openssh openssl yajl-dev zlib-dev cyrus-sasl-dev openssl-dev coreutils curl py-pip

WORKDIR /src/worker
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /src/worker/librdkafka
RUN /src/worker/librdkafka/configure --prefix /usr
RUN make
RUN make install

WORKDIR /src/worker
RUN git clone https://github.com/goccmack/gogll.git
WORKDIR /src/worker/gogll
RUN go install .

WORKDIR /src/worker
COPY worker .

RUN make grammar-gen

RUN go mod download

RUN make build-ci


FROM alpine:latest as runner

RUN apk add --update --no-cache librdkafka librdkafka-dev pkgconf

COPY --from=builder /src/worker/bin .
COPY worker/config ./config

ENTRYPOINT ./worker